### ISSUE TITLE
setters for repeatables

### ISSUE THREAD

**Issue by glenfordwilliams** [dart-lang/protobuf#102]
having a issue where all message fields which are repeatable only have getters and no setters is there a way around this?

i found where the code generation is being done but im not certain how it goes about creating getters and setters for repeatables

**Comment by Kleak** [comment]
I have also the problem :/

**Comment by rakudrama** [comment]
As a work-around, try:
```dart
message.repeatedField..clear()..addAll(values);
```

**Comment by Kleak** [comment]
@rakudrama there is no repeatedField field in the generated class

**Comment by kevmoo** [comment]
CC @mit-mit @sortie

**Comment by sortie** [comment]
CC @athomas

**Comment by sigurdm** [comment]
This is a duplicate of https://github.com/grpc/grpc-dart/issues/107.

The current line is: sse the getter to get the list, and operate on that.
