### ISSUE TITLE
Restore `CodedBufferWriter.writeRawBytes` as public?

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/protobuf#107]
This method was removed in `0.9.0` but the bazel_codegen package uses this in order to output in delimited protobuffer format, https://github.com/dart-lang/bazel_worker/blob/master/lib/src/utils.dart#L7. This is going to block any internal merges.

This delimited proto format is used commonly when sending protobufs over stdin/stdout (which is what blaze uses it for).

Alternatively, could we get an option on `writeToBuffer` which automatically prepends this delimiter to the buffer?

**Comment by jakemac53** [comment]
See `writeDelimitedTo` from the java implementation, https://github.com/google/protobuf/blob/c44ca26fe89ed8a81d3ee475a2ccc1797141dbce/java/core/src/main/java/com/google/protobuf/MessageLite.java#L129

**Comment by keertip** [comment]
@nichite

**Comment by lrhn** [comment]
This is now blocking rolling protobuf 0.9.0 into the Dart SDK.

**Comment by jakemac53** [comment]
Closing in favor of https://github.com/dart-lang/protobuf/issues/109, have a workaround in progress for bazel_worker.
