### ISSUE TITLE
How to   use  PbFieldType.OY  type  in dart?

### ISSUE THREAD

**Issue by QuanjieDeng** [dart-lang/protobuf#108]
In my project  the  "bytes"  in protobuf file translater to Dart  is Lint<int>  type  like:
`message RequestPublicChatHChannel{
    bytes text = 4;   
}`
int  Dart file is :
`
..a<List<int>>(4, 'text', PbFieldType.OY)
`
if i want  a  String  type  to the   'text',how should i to Assignment，thanks!

**Comment by sigurdm** [comment]
If I understand your question correctly you can use

```
import 'dart:convert';

main() {
  Foo foo = Foo.fromBuffer(...);
  String textAsString = utf8.decode(foo.text);
}
```
