### ISSUE TITLE
Keep the actual fieldnames around in BuilderInfo

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/protobuf#153]
For some reason, field names in BuilderInfo are converted to lower camelcase from underscores. This makes it harder to deserialize protos generated by other JSON proto libraries. Eg the Java proto to json serializer or https://github.com/google/protobuf.

If there is an reason to keep the modified field name, it would be nice to provide the actual field name in a different field.

**Comment by NikolayZherebtsovGoogle** [comment]
What happened to these constants? Can't see them in the generated files.

**Comment by sigurdm** [comment]
> What happened to these constants? Can't see them in the generated files.
They are in the `protoname.pbjson.dart` file

**Comment by sigurdm** [comment]
@szakarias This will have to be fixed before we can implement proto3 json en-/decoding.

**Comment by sigurdm** [comment]
Looking into this it seems that the right thing is to use the FieldDescriptorProto.jsonName instead of our own mangled name.
That indeed is converted to camelcase, but with slightly different disambiguations from when we make dart names.
That makes our job simple.

**Comment by sigurdm** [comment]
Reading more we might need both names:
https://developers.google.com/protocol-buffers/docs/proto3#json_options

> Proto3 JSON parsers are required to accept both the converted lowerCamelCase name and the proto field name.

Also textProto requires the proto field name.

That seems to be expensive in terms of size of the compiled program. Will have to consider this further...

**Comment by sigurdm** [comment]
This should be fixed now.
