### ISSUE TITLE
named arguments to set fields in a constructor

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/protobuf#155]
I am not sure if this feature request is worth it, but I wanted to share the idea, so here it is:

What if we take generated messages and make a constructor that takes as arguments the actual fields from the proto buff? for example:

``` proto
message A {
  required someField = 1;
  optional otherField = 2;
}
```

generates:

``` dart
class A extends GeneratedMessage {
  A.filled(this.someField, {this.otherField});
}
```

I just often see patterns where developers have all the data they need to fill in, and end up writing code like:

``` dart
  new A()
      ..someField = a
      ..otherField  = b
```

instead of:

``` dart
  new A(a, otherField: b)
```

**Comment by aloisdeniel** [comment]
I agree ! 

This would be a lot easier to write embedded affectation IMO. Only using named parameters could be even better too  (like Flutter API). You can make named parameter **required** with  [meta](https://pub.dev/documentation/meta/latest/meta/required-constant.html) package.

I find that this kind of instantiation is quite a mess :

```dart
Person()
      ..name = "John"
      ..address = (Address()
         ..street = 5
         ..label = "Baker street"
         ..country = Country(
             ..code = "en"
             ..name = "england"
        )
    )
)
```

The following feels a lot more natural to me, and more aligned with traditional dart APIs : 

```dart
Person(
   name: "John",
  address: Address(
      street: 5,
      label: "Baker street",
      country: Country(code: "en", name: "england")
  )
)
```
