### ISSUE TITLE
documentation for how to use the generated code

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/protobuf#160]
It would probably be useful to have some documentation for how to use the generated code.
 * Reference style documentation
 * Example of how to use the generated code to serialize, deserialize, freeze and what other features are available.

Reading the generated code is not exactly trivial, auto-complete probably gets people far.
But documentation and examples with comments is also a good thing to have.

Note: it's possible that this should be documented somewhere else, or that I missed the docs :)

**Comment by szakarias** [comment]
Fixed.  Official tutorial and documentation can be found at:
https://developers.google.com/protocol-buffers/docs/darttutorial
https://developers.google.com/protocol-buffers/docs/reference/dart-generated
