### ISSUE TITLE
Dart generation on Mac OSX

### ISSUE THREAD

**Issue by jaumard** [dart-lang/protobuf#163]
Hi,

I'm trying to setup protobuf on my MacBook Pro. I've install the proto compiler and put it on my path.

once I try: 
```
protoc --dart_out=. test.proto
``` 
I get 
```
protoc-gen-dart: program not found or is not executable
--dart_out: protoc-gen-dart: Plugin failed with status code 1.
```

Problem is that protoc-gen-dart is on my path and accessible. I able to run it from terminal (but it does nothing and need ^C to kill it).

Any idea what's wrong ?

**Comment by sigurdm** [comment]
Thanks for reporting
This is very weird. On OSX the protoc compiler should find the plugin via `PATH`.
Could you try to give the output of
```
$ echo $PATH
$ which protoc-gen-dart
$ ls -l `which protoc-gen-dart`
```

**Comment by sigurdm** [comment]
If `which` doesn't work that might be a clue!

https://stackoverflow.com/questions/44704710/tilde-char-in-path-e-g-path-bin-usr-bin-bin

Could you try changing your path to:
```
$ export PATH=/Users/jaumard/.fastlane/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jaumard/.pub-cache/bin:/Users/jaumard/flutter/bin:/Users/jaumard/flutter/bin/cache/dart-sdk/bin:/Users/jaumard/Library/Android/sdk/platform-tools/:/Users/jaumard/Library/Android/sdk/tools/bin
```
My guess is that `~` is not understood by `protoc`.

**Comment by jaumard** [comment]
That was my guess too, but it should IMHO :) 
I can confirm that it works with 
```
$ export PATH=/Users/jaumard/.fastlane/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jaumard/.pub-cache/bin:/Users/jaumard/flutter/bin:/Users/jaumard/flutter/bin/cache/dart-sdk/bin:/Users/jaumard/Library/Android/sdk/platform-tools/:/Users/jaumard/Library/Android/sdk/tools/bin
```
I suppose that `$HOME` will not be understood too

**Comment by sigurdm** [comment]
If you use `$HOME` when you set the variable it will be translated before the variable is set.
```
export PATH=$HOME/.fastlane/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.pub-cache/bin:/$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$HOME/Library/Android/sdk/platform-tools/:$HOME/Library/Android/sdk/tools/bin
```
should work fine.

This is pretty much standard behavior for command line tools (`~` is a shell specific convention). But if you think `protoc` should behave different you should raise the issue in: https://github.com/protocolbuffers/protobuf . It is outside the scope of the dart plugin.

I will close this issue now.
