### ISSUE TITLE
Message with map causes exception on freeze()

### ISSUE THREAD

**Issue by kaetemi** [dart-lang/protobuf#165]
![image](https://user-images.githubusercontent.com/1581053/50059290-f27a6680-01bf-11e9-9cdd-c3174dd1b3ad.png)

**Comment by sigurdm** [comment]
Thanks for pointing this out!
Sorry for not reacting to this before. We are working on a fix

**Comment by szakarias** [comment]
Fixed in https://github.com/dart-lang/protobuf/pull/174
