### ISSUE TITLE
Support for google/protobuf/empty.proto

### ISSUE THREAD

**Issue by listepo** [dart-lang/protobuf#170]
test.proto
```
syntax = "proto3";

import "google/protobuf/empty.proto";
```
Error: 
```
file:///Users/ivan/Documents/Bitbucket/demo/services/lib/src/generated/test.pbgrpc.dart:12:8: Error: Error when reading 'file:///Users/ivan/Documents/Bitbucket/demo/services/lib/src/generated/google/protobuf/empty.pb.dart': No such file or directory
import 'google/protobuf/empty.pb.dart' as $0;
```

**Comment by sigurdm** [comment]
Can you write the command you use to compile the proto?
You need to also compile "google/protobuf/empty.proto".

**Comment by listepo** [comment]
```bash

#!/bin/bash

SRC_DIR=./lib/protos
DST_DIR=./lib/src/generated

protoc -I=$SRC_DIR --dart_out=grpc:$DST_DIR $SRC_DIR/*.proto

```

**Comment by sigurdm** [comment]
Try including `google/protobuf/empty.proto` in the command:
```
#!/bin/bash

SRC_DIR=./lib/protos
DST_DIR=./lib/src/generated

protoc -I=$SRC_DIR --dart_out=grpc:$DST_DIR $SRC_DIR/*.proto $SRC_DIR/google/protobuf/*.proto
```

**Comment by listepo** [comment]
`./lib/protos/google/protobuf/*.proto: No such file or directory` because empty.proto in the https://github.com/protocolbuffers/protobuf/tree/master/src/google/protobuf

**Comment by listepo** [comment]
`google/protobuf` system space. For `MacOS + Homebrew` it's `/usr/local/Cellar/protobuf/3.6.1.3_1/include`. Could this be the responsibility of the `protoc_plugin`?

**Comment by opyate** [comment]
> `./lib/protos/google/protobuf/*.proto`: No such file or directory

Try with `$SRC_DIR/google/protobuf/empty.proto` directly, as your shell might not be expanding the wildcard?

**Comment by listepo** [comment]
@sigurdm for example golang protobuf contains https://github.com/golang/protobuf/blob/master/ptypes/empty/empty.pb.go

**Comment by listepo** [comment]
@opyate @sigurdm I understand that if I copy the necessary files into `./lib/protos/google/protobuf/`, everything will work. But ideally, I would like the update of files when new versions were released on the vendor side(`protoc_plugin`) and not the developer.

**Comment by sigurdm** [comment]
I can understand the desire to bundle these with the protoc_plugin.
But I think it is better to get these from the actual source: protoc not from protoc_plugin, that makes one more place where things can get out of date.
Not sure why the Go version has made the other choice.
I'll close this issue as it seems your immediate problem is solved.
If you think we should include the well-known types with the package then please open a separate issue for that.

**Comment by sigurdm** [comment]
If you download protoc as a zip file the archive contains a folder include/ with the well known types

**Comment by listepo** [comment]
@sigurdm thank you for your time

**Comment by devxpy** [comment]
For those on macos (protoc installed using `$ brew install protobuf`), this works well -

```bash
PROTOBUF_DIR="$(brew --prefix protobuf)/include"

protoc *.proto \
    -I $PWD \
    -I $PROTOBUF_DIR
    --dart_out ...
```

**Comment by softronaut** [comment]
I had same issue. I think putting proto files explicitly is not a good idea for the same reason @listepo pointed out.
I would expect the proto file I have created within Go project should work without any hassle.
Can we re-open this issue?

**Comment by netgfx** [comment]
so what is the solution here exactly because I'm running the latest 2.0.0 version and still get this error. The go compiler was importing specifically `empty.proto` and not `*.proto` but it still can't find it in the generated code.

**Comment by bartekpacia** [comment]
I ended up defining my own `Empty` instead of using `google.protobuf.Empty`. Kinda disappointing that a first-party plugin doesn't have this feature.

**Comment by ToMrozek** [comment]
Answer for problem (for Dart, Flutter and Windows 10):

1 # download and unpack "protoc" with "google/protobuf/.protoc" files:
https://github.com/protocolbuffers/protobuf/releases/tag/v23.4
After unpack You will have 2 folder:
- /bin
- /include/google/protobuf

2 # add "C:/..../bin" path to system environment for system and user (it's required to use protoc command from for example cmd console)

3. Check tutorial for Dart from grpc.io site: https://grpc.io/docs/languages/dart/quickstart/
Use command (for example):
protoc --dart_out=grpc:lib/src/generated -I protos protos/helloworld.proto

but after use it You will se problem with google/protobuf/empty.proto, timestamp etc

If You want fixed this problem You need to copy folder start from google (point 2):
google/protobuf/.proto

inside folder with Your protos (in this example) put folder google inside folder protos which have file helloworld.proto inside.

And thats it. After that command protoc --dart_out=grpc:lib/src/generated -I protos protos/helloworld.proto should work without any problem.
