### ISSUE TITLE
Official Dart protobuf documentation

### ISSUE THREAD

**Issue by lucperkins** [dart-lang/protobuf#18]
Anything would be helpful. _Anything_.

**Comment by mit-mit** [comment]
Yes, for now, please checkout the initial documentation on https://github.com/dart-lang/dart-protoc-plugin.

We are working on getting some documentation onto https://developers.google.com/protocol-buffers/ also.

**Comment by sigurdm** [comment]
This is done: https://developers.google.com/protocol-buffers/docs/darttutorial
https://developers.google.com/protocol-buffers/docs/reference/dart-generated
