### ISSUE TITLE
Clone method duplicates data for repeated fields

### ISSUE THREAD

**Issue by Robarelli** [dart-lang/protobuf#194]
To reproduce:

1. Generate a message with a repeated field
2. Create an instance with at least one entry in the repeated field
3. Call clone() on the proto object
4. Inspecting the size of the cloned object's repeated field will be twice as large

I have also tried this inside copyWith() to ensure it is writable, but got the same result

**Comment by sigurdm** [comment]
Thanks for reporting. This sounds quite bad - however I failed to reproduce.

I have tried:

```protobuf
syntax = "proto2";

package third_party.dart.protobuf.test;
option java_package = "com.google.thirdparty.dart.protobuf.test";
option java_outer_classname = "TestProtos";
option java_api_version = 2;

message TopEntity {
  optional int64 id = 1;
  optional string string_value = 2;
  repeated string strings = 3;
  optional SubEntity sub = 4;
  repeated SubEntity subs = 5;
}

message SubEntity {
  optional int64 id = 1;
  optional string string_value = 2;
  repeated string strings = 3;
}
```

```dart
import 'package:fixnum/fixnum.dart';
import 'package:test/test.dart';
import 'package:third_party.dart.protobuf.test/test.pb.dart';

main() {
  test('clone repeated', () {
    final a = TopEntity();
    a.strings.addAll(['a', 'b']);
    a.subs.add(SubEntity());

    final b = a.clone();
    expect(b.strings.length, 2);
    expect(b.subs.length, 1);
  });
}
```
And for me it seems to pass.

What version of protobuf are you using?
Could you provide a more exact reproduction code?

**Comment by sigurdm** [comment]
I'll close this for now. Please reopen if this persists and you can give a reproducing example.
