### ISSUE TITLE
String Type Conflict

### ISSUE THREAD

**Issue by track02** [dart-lang/protobuf#211]
I originally posted this on SO and was advised to make an issue here too
(https://stackoverflow.com/questions/54783804/dart-type-conflicts)

I'm working with a Proto file which defines a number of types to be used within a system, it's not something I have control over and it's causing a conflict after compiling to Dart as one of the defined types is named String which clashes with Dart's core String type

```
syntax = "proto3";

message String {
    string value = 1;
}
```

Which when compiled to Dart gives me 

```
import 'dart:core' show int, bool, double, String, List, Map, override;
import 'package:fixnum/fixnum.dart';
import 'package:protobuf/protobuf.dart' as $pb;
import 'Framework.pbenum.dart';
export 'Framework.pbenum.dart';

class String extends $pb.GeneratedMessage {
  static final $pb.BuilderInfo _i = new $pb.BuilderInfo('String', package: const $pb.PackageName('sila2.org.silastandard'))
    ..aOS(1, 'value')
    ..hasRequiredFields = false
  ;

  String() : super();
  String.fromBuffer(List<int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  // Warning here
  String.fromJson(String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) : super.fromJson(i, r);
  String clone() => new String()..mergeFromMessage(this);
  String copyWith(void Function(String) updates) => super.copyWith((message) => updates(message as String));
  $pb.BuilderInfo get info_ => _i;
  static String create() => new String();
  String createEmptyInstance() => create();
  static $pb.PbList<String> createRepeated() => new $pb.PbList<String>();
  static String getDefault() => _defaultInstance ??= create()..freeze();
  static String _defaultInstance;
  static void $checkItem(String v) {
    if (v is! String) $pb.checkItemFailed(v, _i.qualifiedMessageName);
  }

  // Warning here
  String get value => $_getS(0, '');
  set value(String v) { $_setString(0, v); }
  bool hasValue() => $_has(0);
  void clearValue() => clearField(1);
}
```
Error:
`
Error: The argument type 'String (.../Framework.pb.dart)' can't be assigned to the parameter type 'String (C:\src\flutter\bin\cache\pkg\sky_engine\lib\core\string.dart)'. (argument_type_not_assignable at (.../Framework.pb.dart:50)`

One way around seems to be using a prefix, but I don't really want to be modifying generated code

```
import 'dart:core' show int, bool, double, List, Map, override;
import 'dart:core' as core;

core.String get value => $_getS(0, '');
set value(core.String v) { $_setString(0, v); 
```
I understand this is more of a problem with a poor proto definition but would it be possible or worthwhile to add this prefixing automatically to protoc? Or is there another solution?

**Comment by sigurdm** [comment]
Thanks for reporting.
It is a problem with our generator.
We do have a list of reserved names that will make us modify the name, but that is obviously missing "String".

The real solution is to import dart:core with a prefix. We just never got around to do that.
