### ISSUE TITLE
[Feature] Code First

### ISSUE THREAD

**Issue by listepo** [dart-lang/protobuf#214]
Hello, I would like to be able not to use the proto files if all parts of the project are written in a Dart. Do you have any plans for this? 
For example:
[protobuf-net](https://github.com/mgravell/protobuf-net)
[MagicOnion](https://github.com/Cysharp/MagicOnion)

**Comment by sigurdm** [comment]
Interesting suggestion.
You can look into https://github.com/google/built_value.dart/blob/master/built_value/lib/built_value.dart , It allows you to do declare the fields on abstract classes and get the concrete classes generated. However only with support for serializing to json (but perhaps it could be extended to proto-serialization if that is needed).
I think this is outside the scope of the current project, and we don't currently have the capacity to take on something like this. Therefore I will close this issue for now.
