### ISSUE TITLE
Support well known types in json import/export

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/protobuf#216]
E.g. timestamp should be formatted and understood as: "1972-01-01T10:00:20.021Z".

**Comment by sigurdm** [comment]
We might want to use mixins for the well known types to make this more managable than hard-coding the functions in the generator (as we do now for any and timestamp support).

**Comment by sigurdm** [comment]
https://developers.google.com/protocol-buffers/docs/proto3#json has the details

**Comment by sigurdm** [comment]
cc @szakarias

**Comment by szakarias** [comment]
This is solved with the support of proto3 json. https://github.com/dart-lang/protobuf/pull/274
