### ISSUE TITLE
Proto3 JSON support 

### ISSUE THREAD

**Issue by PavelPZ** [dart-lang/protobuf#220]
I am exchanging protobuf messages by gRPC between CSharp, Java and Dart. Binary format is OK, but Dart has incompatible JSON format (field numbers instead of field names).

**Proto3 (CSharp and Java) format:**

```json
{ "workSpaces": { "localhost": { "csharpServer": { "host": "localhost", "port": 1234 } } } }
```

**Private (Dart) format:**
```json
"{"1":[{"1":"localhost","2":{"1":{"1":"localhost","2":1234}}}]}"

```

**Comment by PavelPZ** [comment]
I am sorry but: what is the reason to mark this PR by **enhancement** flag? As I can read **dart:protobuf  provides runtime support for a Dart implementation of protobufs**. 

Language interoperability is main advantage for protobuf and gRPC technologies so wrong Dart JSON format is serious **bug** (or my misunderstanding)?

**Comment by sigurdm** [comment]
You can call it a bug, or a missing feature.
Don't take the labels too seriously :)

The dart protobuf library was started before proto3 was a thing, so from our perspective every step towards supporting proto3 is an enhancement...

To be more serious, this is already on our road map.

**Comment by PavelPZ** [comment]
Thank you for explanation.
Can you estimate the solution date? For my multiplatform project, I have invested a lot of effort into the using protobuf+gRPC and without this feature I have to redo a lot of code.

**Comment by glenfordwilliams** [comment]
now that #83 is closed what are our options @sigurdm ?

**Comment by sigurdm** [comment]
We don't have a timeline for implementing this. 

If you control the server you might be able to use protobuf binary encoding (GeneratedMessage.toBuffer) from your dart app.

**Comment by mit-mit** [comment]
This is now in code review

**Comment by radvansky-tomas** [comment]
Any update ?

**Comment by sigurdm** [comment]
What updates are you looking for? The issue is closed. https://github.com/dart-lang/protobuf/pull/274 implemented support for proto3 json.

**Comment by danielleiszen** [comment]
Could you please point out in the docs how exactly this feature is supposed to be used? I mean in order to deserialize a JSON with field names instead of field numbers. The default behavior is still field numbers for the generated classes and I really could not find anything about it in the docs. A little hint is enough. Thank you.

**Comment by AlexBurdu** [comment]
Having a somewhat similar issue when trying to deserialize a JSON to a dart class generated from a protobuf message.

The errors is that it's trying to parse my JSON field name to an int.

Here's a screenshot from when debugging this:
![image](https://user-images.githubusercontent.com/1262636/121821240-7f72dd80-cca0-11eb-8d10-bda49124ad35.png)

My JSON looks something like this:
```
{
  "page": 1,
  "pageSize": 10,
  "transactions": [
// omitted values as the deserialization crashes at the first field anyway
]
}
```

**Comment by comigor** [comment]
+1 on this!
It seems `protoc_plugin` is still generating `fromJson` pointing to the old `mergeFromJson` instead of `mergeFromProto3Json`:
```dart
  factory Component.fromJson($core.String i,
          [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) =>
      create()..mergeFromJson(i, r);
```

Maybe it should generate both `fromJson` and a new `fromProto3Json` factories?

Anyway, currently I'm using the following code to parse:
```dart
Component.create()..mergeFromProto3Json(jsonDecode(componentJson));
```

**Comment by comigor** [comment]
MessageGenerator [seems to deal with it already](https://github.com/dart-lang/protobuf/blob/master/protoc_plugin/lib/message_generator.dart#L306-L307) using mixins, but I have no idea (and it seems there's no documentation) on how to use it properly.

**Comment by 50gramx** [comment]
Thank you @comigor for the comment. It's working.
