### ISSUE TITLE
CopyWith() invalidates WhichX() of oneof field X

### ISSUE THREAD

**Issue by khainke** [dart-lang/protobuf#251]
1. Create message with a oneof field x with possible fields x1, x2, x3, ...
2. Create an instance of said message, set one of x1/x2/..., f.e. x1
3. call copyWith
4. call whichX() -> returns notSet

Expected:
4. -> returns Message_X.x1

Edit: adding a reproducable example

test.proto
```proto
syntax = "proto3";

message TestMessage{
    oneof details{
        int32 intDetails= 1;
        string stringDetails = 2;
    }
}
```

copy_with_test.dart
```dart
import 'package:test/test.dart';
import 'package:testpackage/protobuf/dart/test.pb.dart';

void main() {
  group('copyWith tests', () {
    test('copyWith invalidates whichX', () {
      final TestMessage message = TestMessage()..intDetails = 3;

      final TestMessage copy = message.copyWith((_) {});

      expect(copy.hasIntDetails(), isTrue);
      expect(copy.hasStringDetails(), isFalse);
      expect(copy.intDetails, equals(3));
      expect(copy.whichDetails(), equals(TestMessage_Details.intDetails));
    });
  });
}
```

Output:
```
package:test_api                          expect
test\unit_tests\copy_with_test.dart 14:7  main.<fn>.<fn>

Expected: TestMessage_Details:<TestMessage_Details.intDetails>
  Actual: TestMessage_Details:<TestMessage_Details.notSet>
```

**Comment by sigurdm** [comment]
This is indeed a bug. We forget to copy that data to the copied instance.
Thanks for reporting.

**Comment by bsr203** [comment]
Hi @sigurdm I would try to make a reproducible case, but it involve bit effort for me and hope you can get some ideas from the explanation.

I have an issue that when decoding a proto3 json file (created by go using "google.golang.org/protobuf/encoding/protojson"), appropriate data is set for `one of` field, but whichX() -> returns notSet. When I debug, I could see `_fieldSet._oneofCases` is empty at below line.

```int $_whichOneof(int oneofIndex) => _fieldSet._oneofCases[oneofIndex] ?? 0;```
[link](https://github.com/dart-lang/protobuf/blob/master/protobuf/lib/src/protobuf/generated_message.dart#L315)

I populate the data like 
```final all = X()..mergeFromProto3Json(jsonDecode(jsonString));```

Thanks.
bsr

**Comment by sigurdm** [comment]
Hi @bsr203 

I failed to reproduce this:

```
    test('one of', () {
      expect(
          (oneof.Foo()..mergeFromProto3Json({'first': 'foo'}))
              .whichOneofField(),
          oneof.Foo_OneofField.first);
    });
```

And the test passed. Do you think you could find time for making a proper reproduction?

And please open a new issue instead of using an old closed one :)

**Comment by bsr203** [comment]
Thanks @sigurdm Please see the new issue https://github.com/dart-lang/protobuf/issues/425
