### ISSUE TITLE
Any and field_mask are not supported

### ISSUE THREAD

**Issue by dingzuhua** [dart-lang/protobuf#252]
Add appropriate support for any and field_mask

**Comment by sigurdm** [comment]
I believe any is supported.

**Comment by sigurdm** [comment]
For future reference field mask is described here: https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/well-known-types/field-mask

**Comment by sigurdm** [comment]
@szakarias This would probably work poorly together with the field-name removal.

**Comment by dingzuhua** [comment]
> 我相信任何支持。

But the any in proto and field_mask that I compiled to dart reported an error and didn't get support, so what do I do?

**Comment by sigurdm** [comment]
Try to describe in details what code and commands you are running, and what error you are seeing.

**Comment by dingzuhua** [comment]
Targer of URI hasn’t been generated : '../google/protobuf/field_mask.pb.dart'.
Targer of URI hasn’t been generated : '../google/protobuf/any.pb.dart'.

import '../google/protobuf/field_mask.pb.dart' as $0;
import '../google/protobuf/any.pb.dart' as $1;

**Comment by sigurdm** [comment]
The well-known types are not included with the dart protoc. You need to supply and compile them yourself. They can be obtained from the official protobuf package: https://github.com/protocolbuffers/protobuf .

**Comment by dingzuhua** [comment]
I see. Thank you
