### ISSUE TITLE
Failing imports since version "16.0.7"

### ISSUE THREAD

**Issue by aloisdeniel** [dart-lang/protobuf#254]
Since the last version, my generated dart isn't valid anymore. 

Imported packages are now named like `$0`, `$1` (to avoid name conflicts I suppose), but types aren't always refering to those named imports, so the types can't be resolved by the compiler.

With previous version `16.0.5` I had (where `Profiles_UpdateProfile_Request` and `Profiles_CreateProfileResult` are declared in `profiles.pb.dart` :

```dart
import 'profiles.pb.dart';
export 'profiles.pb.dart';

class ProfilesRpcClient extends $grpc.Client {
  static final _$createProfile = $grpc.ClientMethod<
          Profiles_UpdateProfile_Request, Profiles_CreateProfileResult>(
```

Now, with `16.0.7`, I get :

```dart
import 'profiles.pb.dart' as $2;
export 'profiles.pb.dart';

class ProfilesRpcClient extends $grpc.Client {
  static final _$createProfile = $grpc.ClientMethod<
          Profiles_UpdateProfile_Request, Profiles_CreateProfileResult>(
```

I suppose that I should have :
```dart
import 'profiles.pb.dart' as $2;
export 'profiles.pb.dart';

class ProfilesRpcClient extends $grpc.Client {
  static final _$createProfile = $grpc.ClientMethod<
          $2.Profiles_UpdateProfile_Request, $2.Profiles_CreateProfileResult>(
```

As a side note, since all files are also exported, it may leads to conflict too.

**Comment by sigurdm** [comment]
cc @nichite . This seems to have been introduced by https://github.com/dart-lang/protobuf/commit/b61803fdb42754f0eddb63060d9df770ce53017f

**Comment by supermuka** [comment]
I am with the same problem.

`protoc_plugin` versions in my project: 
- "16.0.7" in pubspec.lock
- "17.0.0" when I run `pub global activate protoc_plugin`

**Comment by friddle** [comment]
how to downgrade to solve this problem?

**Comment by sigurdm** [comment]
Add
```
protobuf: 16.0.5
```
To your pubspec until the problem is solved.

**Comment by sigurdm** [comment]
To downgrade write:
```
pub global activate protoc_plugin 16.0.7
```

**Comment by sigurdm** [comment]
There is now version 17.0.1 that should have solved the problem
