### ISSUE TITLE
Allow public access to `enumValues` for map values

### ISSUE THREAD

**Issue by nwparker** [dart-lang/protobuf#276]
note: I'll referring to the [field_info.dart](https://github.com/dart-lang/protobuf/blob/master/protobuf/lib/src/protobuf/field_info.dart) file below:

There exists in `MapFieldInfo` the exposed `CreateBuilderFunc valueCreator`, for creating values of the map. However, a similar construct is not exposed for getting enumValues. This is exposed for normal `FieldInfo` through the variable `final List<ProtobufEnum> enumValues`.
I believe such a variable (perhaps `valueEnumValues`) should be exposed in `MapFieldInfo` as it:
  1. Is valid Proto to have Enums as map values
  2. Follow the pattern of exposing this as is done in `FieldInfo`
  3. Gives developers using this library more flexibility (if they're searching for it)

**Comment by nwparker** [comment]
Following-up here, I think the easiest solution is just making the [_mapEntryBuilderInfo](https://github.com/dart-lang/protobuf/blob/master/protobuf/lib/src/protobuf/field_info.dart#L196) field public.

In addition, we should delete the `valueCreator` field (it's never even being set -- so no one must currently rely on it). See #278

**Comment by nwparker** [comment]
I'm happy to create a PR for this ^

**Comment by sigurdm** [comment]
I think you are right, we should have this available.
A PR is welcome.
