### ISSUE TITLE
`valueCreator` inside of `MapFieldInfo` is never set

### ISSUE THREAD

**Issue by nwparker** [dart-lang/protobuf#278]
The field [valueCreator](https://github.com/dart-lang/protobuf/blob/master/protobuf/lib/src/protobuf/field_info.dart#L193) is never set in the constructor. It likely should be. That or it should be removed

**Comment by sigurdm** [comment]
A fix is already underway as a part of: https://github.com/dart-lang/protobuf/pull/274/files#diff-abc66f026818b7ce8ec053f768829dafR200
