### ISSUE TITLE
Generated code with enum fields and google.protobuf.Any fields do not compile

### ISSUE THREAD

**Issue by hanabi1224** [dart-lang/protobuf#281]
environment: 
flutter 1.7.4
  protoc_plugin: ^18.0.0
  grpc: ^2.1.1
  protobuf: ^0.14.1

Error: Too many positional arguments: 3 expected, but 6 found.
Try removing the extra positional arguments, or specifying the name for named 

method 'e' in builder_info.dart takes 3 positional arguments and 4 named arguments, however, generated code has 6 positional arguments which does not compile. Same happens to method 'a'
![image](https://user-images.githubusercontent.com/6546635/64494458-c52a9700-d2bf-11e9-9063-3b747d585bfe.png)
![image](https://user-images.githubusercontent.com/6546635/64494486-0e7ae680-d2c0-11e9-89a9-326384583d4a.png)

**Comment by hanabi1224** [comment]
looks like i need to reactivate the protoc plugin. This is not a real issue but it will be awesome to document the plugin upgrade process as well. Thanks!

**Comment by sigurdm** [comment]
I will try to remember writing the update command in the changelog moving forward.
`pub global activate protoc_plugin`
