### ISSUE TITLE
No version 0.13.16

### ISSUE THREAD

**Issue by a14n** [dart-lang/protobuf#283]
CHANGELOG mentions 0.13.16 but there's no such version on pub.

**Comment by sigurdm** [comment]
Right - I forgot to publish that one.
Thanks for noticing!
Fixed now.

**Comment by sigurdm** [comment]
Yes the 0.13.16 i published was broken :(
There is now a 0.13.16+1 that reverts to be the same as 0.13.15

**Comment by a14n** [comment]
It works now. Thanks for the update.
