### ISSUE TITLE
Escape invalid option names

### ISSUE THREAD

**Issue by dmdashenkov** [dart-lang/protobuf#285]
When using an option name which clashes with a Dart keyword, the code generator produces code which cannot be compiled.

For instance, I declare a custom option for messages which is called `is`. 
```proto
extend google.protobuf.MessageOptions {
    IsOption is = 73915; 
}
```
When compiled to Dart, the option name is not escaped, so it breaks the Dart code, as `is` is a Dart keyword.

```dart
static final $pb.Extension is = $pb.Extension<IsOption>('google.protobuf.MessageOptions', 'is', 73915, $pb.PbFieldType.OM, defaultOrMaker: IsOption.getDefault, subBuilder: IsOption.create);
```

Unfortunately, I cannot rename the option for a number of reasons.

I suggest that the behaviour here should be similar to what is done for field names — add a symbol to the name so that it is no longer a keyword. If that would be a plain field, it would be named `is_1`, according to a little check I performed.

I use
 - Dart `2.5.0`;
 - Protobuf `3.9.0`;
 - Dart runtime lib and for Protobuf and Dart protoc plugin `0.14.1`.

**Comment by sigurdm** [comment]
Yes that is broken
Thanks for reporting!
