### ISSUE TITLE
Documentation for Proto3 Json Marshal and Unmarshal

### ISSUE THREAD

**Issue by sh0umik** [dart-lang/protobuf#288]
The change log says

> Use GeneratedMessage.toProto3Json() to encode and GeneratedMessage.mergeFromProto3Json(json) to decode.

But the problem is `GeneratedMessage.mergeFromProto3Json` doesn't return `GeneratedMessage`. I am a little confused on json decode into message

Generating json Works fine
`String json = GeneratedMessage.toProto3Json()`

But how can i decode the same `json` into a `GeneratedMessage`

I tried this solution below, but it doesn't work. Getting `Unhandled Exception: FormatException: Invalid radix-10 number (at character 1)`
```
    var msg = GeneratedMessage().createEmptyInstance();
    msg.mergeFromProto3Json(json);
```
But shouldn't the method be like,

`GeneratedMessage message =  GeneratedMessage.mergeFromProto3Json(json)`

**Comment by sigurdm** [comment]
Say your message type is `Foo` do:
```
  Foo().mergeFromProto3Json(json)
```

**Comment by sigurdm** [comment]
`Unhandled Exception: FormatException: Invalid radix-10 number (at character 1)` sounds like there is a problem with the encoding.

Could you make a reproduction? (I need the proto-definition and the faulty json)

**Comment by sh0umik** [comment]
Found the issue . It was a faulty json.
