### ISSUE TITLE
createEmptyInstance is not defined and other errors

### ISSUE THREAD

**Issue by Timmmm** [dart-lang/protobuf#303]
I've build some dart code like this:

    mkdir -p lib/src/generated
    protoc --dart_out=grpc:lib/src/generated -Iprotos protos/foo.proto

It generated some code fine, but there are errors in `foo.pb.dart`:

* `createEmptyInstance` is not defined
* `protoName` is not defined
* `TagNumber` is not defined

I am using the gRPC package:

```
dependencies:
  grpc: ^2.1.2
```

That seems to pull protobuf version 0.13.16+1.

**Comment by Timmmm** [comment]
Ok as I was starting to suspect this is because the newest version of `protoc_plugin` generates code for `protobuf` >= 0.14 which is incompatible with 0.13. You have to *manually* keep them in sync? That sucks.

A better way IMO would be if the you could have the protobuf package that you are actually using generate the source during build (like [Rust](https://docs.rs/prost-build/0.5.0/prost_build/)). Anyway here's how you can manually fix it as if you were some kind of peon or serf:

    pub global activate protoc_plugin 17.0.5

**Comment by sigurdm** [comment]
Yes we are currently not telling a good story for keeping those in sync unfortunately.

If you include `protoc_plugin` in your dev_dependencies the pub version constraint solver makes sure that they are at least matching.

Then to invoke protoc with the right version of the plugin do something like:

```sh
protoc  --dart_out=lib/ -Iprotos/ --plugin "pub run protoc_plugin" protos/*.proto
```

Putting them in one package might actually solve the issue. And treeshaking would ensure the final binary does not pay the cost.

@nichite @szakarias do you have thoughts?

**Comment by Timmmm** [comment]
> `protoc  --dart_out=lib/ -Iprotos/ --plugin "pub run protoc_plugin" protos/*.proto`

That feels like a pretty nice solution! Maybe put that in the readme? Do I just put `protoc_plugin: any` in `dev-dependencies`?

**Comment by sigurdm** [comment]
> Do I just put protoc_plugin: any in dev-dependencies?

Yes, that should give you the newest version compatible with your protobuf version when you upgrade.
