### ISSUE TITLE
$pb.TagNumber Method not found. Error while following Dart Quickstart Guide.

### ISSUE THREAD

**Issue by cdalar** [dart-lang/protobuf#310]
I have followed the process in https://grpc.io/docs/quickstart/dart/ to test drive grpc on dart - server side. 

The repo on https://github.com/grpc/grpc-dart works perfectly before doing modifying the helloworld.proto file and run protoc. Please help. Probably, I'm missing something small. Here are the details. 

Files on gist : 
https://gist.github.com/cdalar/76f65c77b6a80646079a390dcbbaf0eb

cd@Cemals-MacBook-Pro ~/c/g/e/helloworld> pub global list
devtools 0.1.7
protoc_plugin 19.0.1
stagehand 3.3.4
webdev 2.5.2
cd@Cemals-MacBook-Pro ~/c/g/e/helloworld> 

cd@Cemals-MacBook-Pro ~/c/g/e/helloworld> 
protoc --dart_out=grpc:lib/src/generated -Iprotos protos/helloworld.proto
cd@Cemals-MacBook-Pro ~/c/g/e/helloworld> 

cd@Cemals-MacBook-Pro ~/c/g/e/helloworld> dart --version
Dart VM version: 2.5.2 (Tue Oct 8 16:17:11 2019 +0200) on "macos_x64"
cd@Cemals-MacBook-Pro ~/c/g/e/helloworld> 

cd@Cemals-MacBook-Pro ~/c/g/e/helloworld> protoc --version
libprotoc 3.10.0
cd@Cemals-MacBook-Pro ~/c/g/e/helloworld> 

cd@Cemals-MacBook-Pro ~/c/g/e/helloworld> dart bin/server.dart
lib/src/generated/helloworld.pb.dart:33:8: Error: Method not found: 'TagNumber'.
  @$pb.TagNumber(1)
       ^^^^^^^^^
lib/src/generated/helloworld.pb.dart:33:17: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
  @$pb.TagNumber(1)
                ^
lib/src/generated/helloworld.pb.dart:37:8: Error: Method not found: 'TagNumber'.
  @$pb.TagNumber(1)
       ^^^^^^^^^
lib/src/generated/helloworld.pb.dart:37:17: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
  @$pb.TagNumber(1)
                ^
lib/src/generated/helloworld.pb.dart:39:8: Error: Method not found: 'TagNumber'.
  @$pb.TagNumber(1)
       ^^^^^^^^^
lib/src/generated/helloworld.pb.dart:39:17: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
  @$pb.TagNumber(1)
                ^
lib/src/generated/helloworld.pb.dart:35:8: Error: Method not found: 'TagNumber'.
  @$pb.TagNumber(1)
       ^^^^^^^^^
lib/src/generated/helloworld.pb.dart:35:17: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
  @$pb.TagNumber(1)
                ^
lib/src/generated/helloworld.pb.dart:64:8: Error: Method not found: 'TagNumber'.
  @$pb.TagNumber(1)
       ^^^^^^^^^
lib/src/generated/helloworld.pb.dart:64:17: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
  @$pb.TagNumber(1)
                ^
cd@Cemals-MacBook-Pro ~/c/g/e/helloworld>

**Comment by JonasWanke** [comment]
You need to update protobuf in your `pubspec.yaml`. `TagNumber` was introduced in version 0.14.4 (see https://pub.dev/packages/protobuf#0144) and is generated by the code generator starting in version 19.0.0

**Comment by cdalar** [comment]
@JonasWanke Thanks. 
I think it would  be better to update the helloworld example and set protobuf to ^1.0.0 in the repo?

**Comment by NanKang** [comment]
met exactly the same problem. 

After set protobuf to ^1.0.0, and protoc --dart_out=grpc:lib/src/generated -Iprotos protos/helloworld.proto, still  get the same issue.

Am I missing something?

**Comment by boukeversteegh** [comment]
> met exactly the same problem.
> 
> After set protobuf to ^1.0.0, and protoc --dart_out=grpc:lib/src/generated -Iprotos protos/helloworld.proto, still get the same issue.
> 
> Am I missing something?

Did you run `pub get` from the hello-world directory?

**Comment by NanKang** [comment]
> > met exactly the same problem.
> > After set protobuf to ^1.0.0, and protoc --dart_out=grpc:lib/src/generated -Iprotos protos/helloworld.proto, still get the same issue.
> > Am I missing something?
> 
> Did you run `pub get` from the `helloworld` directory?

Hmm, Yeah, I forgot run this... That works, Thanks!
