### ISSUE TITLE
plugin pub run protoc_plugin does not work

### ISSUE THREAD

**Issue by Timmmm** [dart-lang/protobuf#325]
In [this comment](https://github.com/dart-lang/protobuf/issues/303#issuecomment-551077917) and [the current readme](https://github.com/dart-lang/protobuf/blob/master/protoc_plugin/README.md) it is recommended to do the following, but it does not seem to actually work:

```
$ protoc --dart_out=lib/generated backend/protocol/rpc.proto --plugin "pub run protoc_plugin"
protoc-gen-dart: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--dart_out: protoc-gen-dart: Plugin failed with status code 1.
```

Doesn't `--plugin` have to be used like this?

```
$ protoc --foo_out=... --plugin path/to/protoc-gen-foo
```

Looking at the docs for `--plugin`, you can do this:

```
$ protoc --foo_out=... --plugin protoc-gen-foo=path/to/any_binary
```

But the following doesn't work - it wants you to specify an executable, not a command.

```
$ protoc --foo_out=... --plugin protoc-gen-foo="pub run protoc_plugin"
```

**Comment by cnjeffliu** [comment]
I had met the problem too.

**Comment by sigurdm** [comment]
What platform are you on?
It works for me.

**Comment by Timmmm** [comment]
Huh, weirdly I just tried it again and it worked. Very strange.

**Comment by Timmmm** [comment]
(Currently on MacOS 10.14, with Protoc 3.9.1 from brew.)

**Comment by ert485** [comment]
I'm having this problem with an old version of MacOS, and the same thing on Ubuntu 18.04.1

**Comment by ert485** [comment]
Found a strange workaround, make this file as `plugin.bash`
``` bash
#!/bin/bash
pub run protoc_plugin
```
and run with 
`protoc -I ./ --dart_out ./ test.proto --plugin=protoc-gen-dart="./plug.bash"`

**Comment by sigurdm** [comment]
@ert485 What is the exact command that is failing?

**Comment by ert485** [comment]
In Ubuntu 18.04.1:
`protoc -I ../ --dart_out ../ ../test.proto --plugin=protoc-gen-dart="pub run protoc_plugin"` fails with:
```
pub run protoc_plugin: progam not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--dart_out: protoc-gen-dart: Plugin failed with status code 1.

**Comment by sigurdm** [comment]
Try doing:

```
 protoc-I ../ --dart_out ../ ../test.proto --plugin="pub run protoc_plugin"
```

That seems to work.
I don't know why it makes a difference, it might be a bug in protoc.

**Comment by sigurdm** [comment]
Here's the documentation from `protoc --help`. I'm not sure how to exactly interpret it
```
  --plugin=EXECUTABLE         Specifies a plugin executable to use.
                              Normally, protoc searches the PATH for
                              plugins, but you may specify additional
                              executables not in the path using this flag.
                              Additionally, EXECUTABLE may be of the form
                              NAME=PATH, in which case the given plugin name
                              is mapped to the given executable even if
                              the executable's own name differs.
```

**Comment by sigurdm** [comment]
Sorry - I was mistaken - it newer ran the right plugin for me, it ran the one i had in my path.

This has seemingly never worked - not sure how I could be convinced for so long -- embarrassing

**Comment by Timmmm** [comment]
Ah is the issue that `--dart_out --plugin="this_doesnt_exist"` silently works if you have `protoc-dart` or whatever in your `PATH`?

**Comment by sigurdm** [comment]
> Ah is the issue that --dart_out --plugin="this_doesnt_exist" silently works if you have protoc-dart or whatever in your PATH?

yes exactly

I will probably have to revert the README.

**Comment by cnjeffliu** [comment]
In Ubuntu18.04, I just tried it again and it works.
But on Windows ,It may be unsupported.

**Comment by sigurdm** [comment]
@cnjeffliu what happens if you run:
```
$ which protoc-gen-dart
```
My guess is that you have a global dart protoc plugin installed, and that gets used instead of the plugin.

**Comment by cnjeffliu** [comment]
@sigurdm 
the plugin is exist in /d/github/dart_pb/protoc_plugin/bin/protoc-gen-dart

**Comment by sigurdm** [comment]
https://github.com/dart-lang/protobuf/pull/344 reverted the documentation

**Comment by boukeversteegh** [comment]
the issue of a binary suddenly working: sounds like you've installed something on your $PATH, but it wasn't loaded into $PATH until you've reopened your terminal
