### ISSUE TITLE
bug in _permissiveCompare?

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/protobuf#327]
I believe from inspection that `_permissiveCompare` has a bug:

https://github.com/dart-lang/protobuf/blob/master/protobuf/lib/src/protobuf/proto3_json.dart#L419

```
/// Returns true if [a] and [b] are the same ignoring case and all instances of
///  `-` and `_`.
bool _permissiveCompare(String a, String b) {
  const dash = 45;
  const underscore = 95;

  // Enum names are always ascii.
  int i = 0;
  int j = 0;

  outer:
  while (i < a.length && j < b.length) {
    int ca = a.codeUnitAt(i);
    if (ca == dash || ca == underscore) {
      i++;
      continue;
    }
    int cb = b.codeUnitAt(j);
    while (cb == dash || cb == underscore) {
      j++;
      if (j == b.length) break outer;
      cb = b.codeUnitAt(j);
    }

    if (ca != cb && (ca ^ cb != 0x20 || !_isAsciiLetter(ca))) return false;
    i++;
    j++;
  }
  return true;
}
```

Consider `_permissiveCompare('a', '-')`. The second while loop breaks out without ever comparing `'a'`.
Consider `_permissiveCompare('', 'a')`. The first loop exits and there is no check for unmatched characters in the second input.

Considering these problems, I suggest the `_permissiveCompare` has unit tests.

**Comment by sigurdm** [comment]
Thanks for looking through this!
I'll work on a fix
