### ISSUE TITLE
Add a support for oneof

### ISSUE THREAD

**Issue by goj** [dart-lang/protobuf#33]
https://developers.google.com/protocol-buffers/docs/proto#oneof

Generating enum and being able to switch on which field is set (like in Java proto library) would be especially useful.

**Comment by gamebox** [comment]
I don't think this would be terribly difficult to implement, and not having it really dampens the usefulness of the plugin for the use cases in which I typically want to use protobuf.

Unless this assigned internally, I wouldn't mind submitting a PR as I'm hoping to use this for a Flutter side-project.

**Comment by szakarias** [comment]
PRs are always welcome, but I am also starting to look at this, so it should be supported soon.

**Comment by szakarias** [comment]
Fixed by https://github.com/dart-lang/protobuf/pull/166 .
