### ISSUE TITLE
Any.pack() sets typeUrl to '/packagename.messagename' when typeUrlPrefix is set to empty string

### ISSUE THREAD

**Issue by chinmaygit** [dart-lang/protobuf#338]
The default type URL for a given message type is `type.googleapis.com/packagename.messagename`.
I wanted to set `packagename.messagename` as type URL without prefix, Any.pack method does not let me do that as it sets prefix `/` when typeUrlPrefix is set to empty string.

protobuf v1.0.1

Expected result: typeUrl: 'packagename.messagename'

Actual result: typeUrl: '/packagename.messagename'

## Workaround
```
var authData = AuthData()
requestMessage.authData = Any.pack(authData);
requestMessage.authData.typeUrl = authData.info_.qualifiedMessageName;
```
## Solution
```
static void packIntoAny(AnyMixin target, GeneratedMessage message,
      {String typeUrlPrefix = 'type.googleapis.com'}) {
    target.value = message.writeToBuffer();
    const typeUrl = typeUrlPrefix.isNotEmpty
        ? '${typeUrlPrefix}/${message.info_.qualifiedMessageName}'
        : '${message.info_.qualifiedMessageName}';
    target.typeUrl = typeUrl;
  }
```
After above change it can be written something like this
```
var authData = AuthData()
requestMessage.authData = Any.pack(authData, typeUrlPrefix: '');
```

**Comment by sigurdm** [comment]
Is there precedence for this behavior?
What happens in java/go/c++ with an empty url prefix?

**Comment by chinmaygit** [comment]
> Is there precedence for this behavior?
> What happens in java/go/c++ with an empty url prefix?

looks like 
default value comes with '/' suffix, in C++
`const char kTypeGoogleApisComPrefix[] = "type.googleapis.com/";`

we can follow same pattern here

**Comment by sigurdm** [comment]
Changing the prefix to include the '/' would be a breaking change.

Looking at https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/java/java_message.cc#L1373

```
    "private static String getTypeUrl(\n"
    "    java.lang.String typeUrlPrefix,\n"
    "    com.google.protobuf.Descriptors.Descriptor descriptor) {\n"
    "  return typeUrlPrefix.endsWith(\"/\")\n"
    "      ? typeUrlPrefix + descriptor.getFullName()\n"
    "      : typeUrlPrefix + \"/\" + descriptor.getFullName();\n"
```
and for c#
https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf/WellKnownTypes/AnyPartial.cs

```
 private static string GetTypeUrl(MessageDescriptor descriptor, string prefix) =>
            prefix.EndsWith("/") ? prefix + descriptor.FullName : prefix + "/" + descriptor.FullName;
```

it seems there is always a '/'.

**Comment by chinmaygit** [comment]
you are right '/' is always there, i edited my previous comment.
So what's the solution here?
I have to send type_url_prefix?

**Comment by sigurdm** [comment]
> Is there any protobuf specs

The relevant specs I know about are in: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/any.proto and they are very vague about what the URL means. They explain empty scheme, but not relative urls.

> So what's the solution here?

I guess it depends on your use-case. The current code supports unpacking Any's with no prefix. And I would hope your node JS backend knows how to handle(ignore) arbitrary url prefixes, if that is the case you can simply just use the default.

**Comment by chinmaygit** [comment]
It looks like, all libraries are enforcing to use typeUrlPrefix.
I am closing this issue. Thank you
