### ISSUE TITLE
Unable to call `GeneratedMessage.setField()` for map types

### ISSUE THREAD

**Issue by nwparker** [dart-lang/protobuf#340]
It appears it is not possible to call `GeneratedMessage.setField()` for map types. More specifically, in attempting to do so, one is always met with an error of the form:
`Illegal to set field map(4) of User to value ({}): not a GeneratedMessage`

This appears to be an issue in `field_error.dart`'s [_getFieldError()](https://github.com/dart-lang/protobuf/blob/master/protobuf/lib/src/protobuf/field_error.dart#L12) method. There is no matching statement for `PbFieldType._MAP` type.

I have a fix for this (you can see my branch/commit [here](https://github.com/nwparker/protobuf/commit/93d4c10db5f9cf70c4a83f39e21a99bd9c02dbdf)). Happy to contribute a PR.

Please let me know if this seems reasonable and I shall proceed. Thanks!

**Comment by sigurdm** [comment]
Thanks for the proposal. It doesn't fit very well with the current data-model though.

You also cannot set a repeated field.

We maintain the invariant that repeated fields are represented by a PbList and Map fields are represented with a PbMap, that is because we hack the equality and hash-codes, they also implement deep cloning. Therefore it is not allowed to set these to any map.

The right way to set a map-field to have the same values as `otherMap` would be:

```
final map = message.getField(4)
map.clear();
map.addAll(otherMap);
```

**Comment by dave** [comment]
Hi @sigurdm if the map field isn't set (e.g. it's null), then this will fail... in this case, it looks like `getField` returns the default value, and updates to that value are not reflected in `message`... I've prepared a simplified example:

```proto
message Holder {
  map<string, int32> numbers = 1;
}
```

```dart
setNumber(Holder holder) {
  var map = holder.getField(1);
  map["a"] = 1;
}

void main() {
  
  // TEST FAILS:
  test("empty map", () {
    var holder = Holder();
    setNumber(holder);
    expect(holder.numbers["a"], 1);
  });

  // TEST PASSES:
  test("not empty map", () {
    var holder = Holder()..numbers["b"] = 2;
    setNumber(holder);
    expect(holder.numbers["a"], 1);
  });

}
```

Is there any way around this? It seems like I should be able to do something like:

```dart
if (holder.getFieldOrNull(1) == null) {
  holder.setField(1, holder.getDefaultForField(1));
}
```

... but that fails with the above error.
