### ISSUE TITLE
"Custom Options"  not support

### ISSUE THREAD

**Issue by songfei** [dart-lang/protobuf#341]
https://developers.google.com/protocol-buffers/docs/proto#customoptions

Custom Options
Protocol Buffers even allow you to define and use your own options.

For example:
```
import "google/protobuf/descriptor.proto";

extend google.protobuf.MessageOptions {
  optional string my_option = 51234;
}

message MyMessage {
  option (my_option) = "Hello world!";
}
```
Here we have defined a new message-level option by extending MessageOptions. When we then use the option, the option name must be enclosed in parentheses to indicate that it is an extension. We can now read the value of my_option in C++ like so:
```
string value = MyMessage::descriptor()->options().GetExtension(my_option);
```
Here, MyMessage::descriptor()->options() returns the MessageOptions protocol message for MyMessage. Reading custom options from it is just like reading any other extension.

Similarly, in Java we would write:
```
String value = MyProtoFile.MyMessage.getDescriptor().getOptions()
  .getExtension(MyProtoFile.myOption);
```
In Python it would be:
```
value = my_proto_file_pb2.MyMessage.DESCRIPTOR.GetOptions()
  .Extensions[my_proto_file_pb2.my_option]
```

**Comment by chinmaygit** [comment]
I think Custom options are supported in proto2 and dart library supports only proto3

**Comment by sigurdm** [comment]
> I think Custom options are supported in proto2 and dart library supports only proto3

This is not true. dart protobuf supports proto2 and proto3. Also proto3 supports custom options (see https://developers.google.com/protocol-buffers/docs/proto3#custom_options)

We do output descriptors in `.pbjson.dart` files, but they are in json format, that does not preserve the extensions.

The solution as I see it is to output the descriptors using the binary encoding, then they can be decoded using any desired extensions.

**Comment by peter-meemo** [comment]
Just checking in, this issue has been open for over a year. Is there any timeline for completing this?

**Comment by sigurdm** [comment]
This is actually fixed (by emitting a binary version of the descriptor) in the google-internal version protobuf.

@iinozemtsev do you have cycles to export this (cl/302638810)?

**Comment by iinozemtsev** [comment]
Yes, I'll prepare a PR (most likely just finish #406) early next week

**Comment by sigurdm** [comment]
Oh - you are already on this! Thanks!

**Comment by iinozemtsev** [comment]
The change is merged, @sigurdm could you publish it?

**Comment by sigurdm** [comment]
Done
