### ISSUE TITLE
Proto3 JSON, default values and hasX

### ISSUE THREAD

**Issue by khainke** [dart-lang/protobuf#342]
Edit: I messed up my test, current behavior is actually as i would expect, apparently against proto3 standard, but arguably more useful this way, maybe should be documented or renamed, but i actually like, how it works right now...

I don't understand the thought process behind the decisions regarding default values and proto3Jsons. For integer fields there is usually a clear difference between explicitly setting the value to 0 and not setting it. this could be easily represented in the json by either not having the value show up in the map or having it show up with an explicit value of 0. I can't think of a reason why it could not work in this way. In fact, hasX exactly works like this for created messages on the dart side. when i create a generated message, it returns false for not set fields and after setting them on default values it returns true.  

```protobuf
message X{
  int n = 1;
}
```

```dart
X nNotSet=X();
X nSet = X()..n=0; 
```

Current Behavior (i like this):
```dart
nNotSet.toProto3Json() == {};
nSet.toProto3Json() == {"n":0};
```

Behavior defined in standard (i dislike this):
```dart
nNotSet.toProto3Json() == {};
nSet.toProto3Json() == {};
```

I know, google proto3 standard, for some weird reason, states:

> If a value is missing in the JSON-encoded data or if its value is null, it will be interpreted as the appropriate default value when parsed into a protocol buffer. If a field has the default value in the protocol buffer, it will be omitted in the JSON-encoded data by default to save space. An implementation may provide options to emit fields with default values in the JSON-encoded output.

 
But this is not space-saving, this is making values not well-behaved, hard to interpret and it breaks hasX over encoding and decoding... And i am not sure, in what case it would ever help somebody, that an explicitly set value is omitted... 
(edited:) So i would argue for keeping the current implementation, maybe rename it or make the inconsistency to standard clear in documentation or something, but i think its more useful the way it is. I just messed up my tests, and thought the implementation might strictly follow the standard, but it actually works in a way, that is essentiel for me right now.

**Comment by sigurdm** [comment]
I see the opposite behavior (maybe that's what you meant?)

```pb
syntax = "proto3";

message X {
  int32 i = 1;
}
```

```dart
import 'package:blah/sample.pb.dart';

main() {
  final a = X()..i = 0;
  final b = X();
  print(a.toProto3Json());
  print(b.toProto3Json());
}
```
prints:

```
dart bin/test.dart
{i: 0}
{}
```

We should not have the hasX getter on proto3 scalar fields. They should not exist, and better not be relied upon.

This is an open issue, which we have not got around to: https://github.com/dart-lang/protobuf/issues/164

That also indicates that the current behavior is buggy. For proto3 messages when encoding scalar fields we should first check if they are 0, and if true we should not output them. For proto2 messages we should be more careful. There is a hasX behavior to preserve. I don't think that is specified, but I think the obvious choice is to leave the value out iff it is not set.

> Note that for scalar message fields, once a message is parsed there's no way of telling whether a field was explicitly set to the default value (for example whether a boolean was set to false) or just not set at all: you should bear this in mind when defining your message types. For example, don't have a boolean that switches on some behaviour when set to false if you don't want that behaviour to also happen by default. Also note that if a scalar message field is set to its default, the value will not be serialized on the wire.

**Comment by khainke** [comment]
I messed up my tests, sry for confusing issue post, can see that the current behavior actually matches my expected/wanted behavior, it might not match exactly to proto3, but is actually more useful. I close the issue, since theres nothing that bothers me anymore, but it could be a documentation/naming/standards issue, but that is apparently already raised.
