### ISSUE TITLE
ServiceClient does not extend ServiceBase

### ISSUE THREAD

**Issue by szotp** [dart-lang/protobuf#343]
All ServiceClients in my generated code also contain corresponding ServiceBases. 

I was thinking about using service bases so I can easily mock them in my tests, but clients do not implement them.

So I'm wondering what is even the purpose of those bases. Is this somehow related to JavaScript compilation (I'm using this in flutter app).

**Comment by sigurdm** [comment]
They are intended to be implemented by a server implementing the back-end of those services.

**Comment by szotp** [comment]
Now I get it, thanks.
