### ISSUE TITLE
How to convert from Json in dart to Protobuf ?

### ISSUE THREAD

**Issue by ahyangnb** [dart-lang/protobuf#384]
https://stackoverflow.com/questions/38406211/how-to-convert-from-json-to-protobuf

That is the question, what should I do with Dart?

**Comment by ahyangnb** [comment]
solved

**Comment by patrickboulay** [comment]
How you did it? I tried this:  [https://github.com/dart-lang/protobuf/issues/446](https://github.com/dart-lang/protobuf/issues/446)
But it's not working..
