### ISSUE TITLE
Does this plugin support Any?

### ISSUE THREAD

**Issue by ondev** [dart-lang/protobuf#398]
in my proto3 file. There are import "google/protobuf/any.proto";

But in generated dart code,  error at: import 'google/protobuf/any.pb.dart'

**Comment by songfei** [comment]
The answer is  YES!

You need to generate the `google/protobuf/any.proto` file yourself in your project

**Comment by wengxianxun** [comment]
how

**Comment by sigurdm** [comment]
Put https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/any.proto in `google/protobuf/any.proto` next to your other `.proto` files when compiling.
