### ISSUE TITLE
Why do pb messages throw when setting a null value?

### ISSUE THREAD

**Issue by enyo** [dart-lang/protobuf#40]
I'm just curious about the design decision to throw in this case. Now you always have to do those checks:

``` dart
if (foo != null) pbMessage.foo = foo;
```

Couldn't it simply [return instead of throwing](https://github.com/dart-lang/dart-protobuf/blob/master/lib/src/protobuf/generated_message.dart#L1003) when `value` is `null`.

**Comment by skybrian** [comment]
I don't know who made the decision, but I think the idea is to detect programming errors where you accidentally set a field to the wrong value.

In your example, if "foo" is never supposed to contain a null then you shouldn't add the if statement. Instead you should debug it to find where the null came from. If it's user input then maybe the program should detect it earlier and indicate an error somehow?

This is consistent with how the protobuf library detects other errors like attempting to put a string in an int32 field. But I admit it's more inconvenient when you're working with variables where a null is normal.

**Comment by sigurdm** [comment]
This is to make it explicit that you'll get the default message when getting the field next time.
This works as intended (same behavior in java).
