### ISSUE TITLE
[protobuf] Looks like package pub.dev is out of date.

### ISSUE THREAD

**Issue by slightfoot** [dart-lang/protobuf#414]
https://pub.dev/packages/protobuf shows `1.0.1` and `pubspec.yaml` in repo shows `1.1.0`.

Lots of changes and releases in CHANGELOG.
https://github.com/dart-lang/protobuf/blob/master/protobuf/CHANGELOG.md

Can someone publish the package so we can get some of the bug fixes?

**Comment by mraleph** [comment]
Published.
