### ISSUE TITLE
Is null operator (??) not working as expected

### ISSUE THREAD

**Issue by cohenadair** [dart-lang/protobuf#423]
## Overview

The `??` operator always invokes the "is null" clause, regardless of if the left side of the operator is `null`. In addition, properties from the non-null object are copied into the result of the "is null" case.

For example:
```dart
Animal pet = Animal()
  ..name = "Dog"
  ..numberOfLegs = 4;
Animal pet2 = pet ?? Animal()..name = "Cat";
String name = pet2.name; // Equals "Cat", but should equal "Dog"
int numberOfLegs = pet2.numberOfLegs; // Equals 4, but should equal 0
```
A workaround is to simply use the `??=` operator:
```dart
Animal pet = Animal()..name = "Dog";
pet ??= Animal()..name = "Cat";
String name = pet2.name;
```

## Reproduction Steps

Given the following message definition in proto3:
```protobuf
message Animal {
  string name = 1;
  int32 number_of_legs = 2;
}
```
Then run the following dart program:
```dart
import 'package:mobile/model/gen/anglerslog.pb.dart';

class NonPbAnimal {
  String name;
  int numberOfLegs;

  NonPbAnimal(this.name, this.numberOfLegs);

  @override
  String toString() => "name=$name, numberOfLegs=$numberOfLegs";
}

main() {
  // Step 1
  Animal dog = Animal()
    ..name = "Dog"
    ..numberOfLegs = 4;
  print("$dog\n");
  // Prints:
  // name: Dog
  // numberOfLegs: 4

  // Step 2
  Animal cat = dog?.clone() ?? Animal() // dog ?? Animal() yields the same
    ..name = "Cat";
  print("$cat\n");
  // Prints:
  // name: Cat
  // numberOfLegs: 4
  // The "is null" clause of ?? is invoked, and "numberOfLegs" is copied from
  // dog, but name is reset. The "is null" clause should not be invoked.

  // Step 3
  Animal dogClone = dog?.clone();
  if (dogClone == null) {
    dogClone = Animal()
      ..name = "Cat";
  }
  print("$dogClone\n");
  // Prints:
  // name: Dog
  // numberOfLegs: 4
  // This is what I would expect from the ?? example above.

  // A non-protobuf example works as expected.

  NonPbAnimal nonPbDog = NonPbAnimal("Dog", 4);
  print("$nonPbDog\n\n");
  // Prints:
  // name=Dog, numberOfLegs=4

  NonPbAnimal nonPbCat = nonPbDog ?? NonPbAnimal("Cat", 4);
  print("$nonPbCat\n\n");
  // Prints:
  // name=Dog, numberOfLegs=4
}
```
As shown in the example, a normal (non-protobuf) class works as expected.

Perhaps there is something about protobuf I'm unaware of regarding this issue. I wasn't able to find anything in the documentation, but regardless, I would expect the `??` to work as documented in the Dart language.

**Comment by sigurdm** [comment]
I don't think this has to do with protobuf. This Simple program has the same behaviour:
```dart
main() {
  Animal pet = Animal()
    ..name = "Dog"
    ..numberOfLegs = 4;
  Animal pet2 = pet ?? Animal()..name = "Cat";
  print('${pet2.name} ${pet2.numberOfLegs}');
}

class Animal {
  String name;
  int numberOfLegs = 0;
}
```

prints "Cat 4". The `..name="Cat"` is applied after the `??` decides that `pet` is not null, so we change the `name` field.

Maybe you meant to write:
```
main() {
  Animal pet = Animal()
    ..name = "Dog"
    ..numberOfLegs = 4;
  Animal pet2 = pet ?? (Animal()..name = "Cat");
  print('${pet2.name} ${pet2.numberOfLegs}');
}

class Animal {
  String name;
  int numberOfLegs = 0;
}
```
We get "Dog 4"

**Comment by cohenadair** [comment]
@sigurdm, thanks for that. Indeed, it doesn't look like a protobuf issue, but an issue with my understanding of dart's order of operations when using the cascade operator.

In the statement: `Animal pet2 = pet ?? Animal()..name = "Cat";`, I expected `Animal()..name = "Cat";` to be evaluated first and applied to the "is null" clause of ??, like it is in your example after adding parentheses. When actually, the `pet ?? Animal()` is evaluated first, then the `..name = "Cat"` is evaluated.

Closing this as not an issue. Thanks again.
