### ISSUE TITLE
fromJson() not working

### ISSUE THREAD

**Issue by patrickboulay** [dart-lang/protobuf#446]
I have an issue with the fromJson() function.
I try to build my protobuf with the data received from Firestore and the fromJson() seems to not be able to parse it.
Facing this issue, I decide to do a test by creating a new empty Protobuf manually, export it as a JSON and create a new protobuf with the json. I got some weird issues:

```
MyProtobuf my_protobuf = MyProtobuf();
my_protobuf.id = "ABC";

...
// Exporting using writeToJson()
 String json1 = my_protobuf.writeToJson(); // All my keys are numbers.. why?

// Exporting using a Map
Map<String, dynamic> json2_map = info_to_write.toProto3Json();
String json2 = JsonEncoder().convert(json2_map); // Seems to be a normal JSON

// Build a protobuf from JSON
MyProtobuf new_protobuf1 = MyProtobuf.fromJson(json1);  // Exception thrown
MyProtobuf new_protobuf2 = MyProtobuf.fromJson(json2); // Exception thrown
```

Is this a bug of Im not using this good function?

**Comment by arnemolland** [comment]
@patrickboulay I encountered the same issue. `fromJson()` tries to parse the keys as integers representing the protobuf field value, which is why it was failing to parse. Instead of using `SomeObject.fromJson()`, use `SomeObject()..mergeFromProto3Json()`. This resolved the issue in my case at least.

**Comment by sigurdm** [comment]
Yes - the `fromJson` and `toJson` uses an old json format where the keys are the numbers. This is explained here: https://github.com/dart-lang/protobuf/blob/master/protobuf/lib/src/protobuf/generated_message.dart#L211

`mergeFromProto3Json`  is the correct way of using the new proto3 json format.
