### ISSUE TITLE
Failed to compile proto to dart with `import "google/protobuf/struct.proto"`

### ISSUE THREAD

**Issue by xinxiao** [dart-lang/protobuf#448]
Generated a relative path; it appears to be that there isn't a global dart package for well known proto types and the compiler just treated the import as an average file import

**Comment by sigurdm** [comment]
We don't treat the well known protos special. You have to include it in your project.
It can be downloaded here: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/struct.proto

This has been discussed here: https://github.com/dart-lang/protobuf/issues/170
