### ISSUE TITLE
Dart mergefromproto3json doesn't set oneof properly

### ISSUE THREAD

**Issue by steeling** [dart-lang/protobuf#467]
Trying to do a type switch on a oneof field, from the generated `which` method, but defaults to not set.

ie:

```
message Temp {
  oneof state {
     string state_one = 1;
     string state_two = 2;
  }
}
```

```
mypb = pb.Temp()..mergefromproto3json(myJsonObj)
mypb.whichState() => Temp_State.notSet
mypb.stateTwo => "state two is actually set!"
```

**Comment by sigurdm** [comment]
This was fixed in https://github.com/dart-lang/protobuf/commit/2d80431100d52347fe7ddc52cc021be2ee83c978 .
Seems it is high time for a release.

**Comment by sigurdm** [comment]
Now releases
