### ISSUE TITLE
why dart ProtoBuf doesn't support null value like nodejs Protobuf ?

### ISSUE THREAD

**Issue by redDwarf03** [dart-lang/protobuf#472]
Hello

why dart ProtoBuf doesn't support null value like nodejs Protobuf ?
I would like communicate with nodejs ProtoBuf message who accept null value but dart ProtoBuf seems don't accept null value.
Thank you for help

**Comment by sigurdm** [comment]
Instead of 
```
  message.field = null;
```
Do
```
  message.clearField();
```

This follows the java protobuf design.

**Comment by redDwarf03** [comment]
thank you for your answer.
but sadly,  clearField doesn't return null and I have to communicate with a nodejs proto who wait sometimes for null value..... :/

**Comment by iinozemtsev** [comment]
What do you mean by accepting null values? There's no notion of nulls in protobufs itself -- no mentions of nulls in proto2 language guide, https://developers.google.com/protocol-buffers/docs/proto, and proto3 language guide mentions nulls only in a context of json: https://developers.google.com/protocol-buffers/docs/proto3#json

Is your issue related to json (de)serialization?

**Comment by redDwarf03** [comment]
in js, when I call this function: 
```
fromBytes(bytes) {
    const protoTx = messages.ProtoTransaction.deserializeBinary(bytes); 
    ...
}
```
i obtain for example values: 

```
protoTx: proto.models.ProtoTransaction
array: Array(1)
0: Array(6)
0: 11
1: 63
2: null
3: Uint8Array(20) [244, 41, 227, 109, 104, 190, 16, 66, 141, 115, 7, 132, 57, 21, 137, 87, 46, 224, 247, 43]
4: Uint8Array(8) [13, 224, 182, 179, 167, 100, 0, 0]
5: Uint8Array(8) [13, 224, 182, 179, 167, 100, 0, 0]
length: 6
__proto__: Array(0)
length: 1
__proto__: Array(0)
arrayIndexOffset_: -1
```

The def of the message is

```
syntax = "proto3";
package models;

//protoc --js_out=import_style=commonjs,binary:./ proto/models.proto

message ProtoTransaction {
    message Data {
        uint32 nonce = 1;
        uint32 epoch = 2;
        uint32 type = 3;
        bytes to = 4;
        bytes amount = 5;
        bytes maxFee = 6;
        bytes tips = 7;
        bytes payload = 8;
    }
    Data data = 1;
    bytes signature = 2;
    bool useRlp = 3;
}
```

The 3 properties payload, tips and type are not instanciate (type = null and payload and tips are not in the data properties. 
in dart, with the same definition of message ProtoTransaction, I obtain

```
0: 11
1: 63
2: 0
3: Uint8Array(20) [244, 41, 227, 109, 104, 190, 16, 66, 141, 115, 7, 132, 57, 21, 137, 87, 46, 224, 247, 43]
4: Uint8Array(8) [13, 224, 182, 179, 167, 100, 0, 0]
5: Uint8Array(8) [13, 224, 182, 179, 167, 100, 0, 0]
6: [0]
7: []
```
 So 2, 6 and 7 haven't got the same value..

**Comment by iinozemtsev** [comment]
At least for `2` (if it corresponds to `uint32 epoch = 2;`) Dart behavior seems correct to me according to https://developers.google.com/protocol-buffers/docs/proto3#default:

> When a message is parsed, if the encoded message does not contain a particular singular element, the corresponding field in the parsed object is set to the default value for that field.
> ...
> * For numeric types, the default value is zero.

Dart protoc_plugin can also generate methods like `hasEpoch()`, which you can use instead of comparing value to null if you use protoc_plugin later than 19.2.1 and protoc later than [3.12.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0). It may also require changing proto definition to add `optional` to field definition, e.g. `optional uint32 epoch`, but I am not sure.

Unfortunately I am not sure about fields 6 and 7 without knowing actual bytes

**Comment by redDwarf03** [comment]
thanks for you reply
