### ISSUE TITLE
How to generate null safe files that aren't .pbgrpc?

### ISSUE THREAD

**Issue by acoutts** [dart-lang/protobuf#476]
I want to generate some `.pb.dart` files amongst others that aren't `.pbgrpc`. The grpc files are looking good on the latest 2.0.0 release (null safe code), but everything else is still being generated as legacy code.

Ex:
```dart
///
//  Generated code. Do not modify.
//  source: google/protobuf/any.proto
//
// @dart = 2.3
// ignore_for_file: camel_case_types,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name,return_of_invalid_type
```

How can I make the protoc plugin output these with null safe code too?

**Comment by iinozemtsev** [comment]
It looks like this header is generated with an older version of protoc_plugin. Current protoc_plugin (20.0.0) should unconditionally generate `@dart =2.12` and a longer list of rules to ignore for file: https://github.com/dart-lang/protobuf/blob/d53d2bba4273088212affbc4ab4bfc561205d9fa/protoc_plugin/lib/file_generator.dart#L596-L597

**Comment by acoutts** [comment]
Ah! You're right- I had some legacy code I was not actually generating. Very cool, it works!
