### ISSUE TITLE
Init model from JSON error with message: "Invalid radix-10 number"

### ISSUE THREAD

**Issue by gl-ihorkoblan** [dart-lang/protobuf#501]
I have json string of an GRPC model. And try to fulfil GRPC model from json like:

```
try {
    final String info = await _methodChannel.invokeMethod(GRPCMethod.getDeviceInformation); // Getting json from native grpc model
      var response = GetDeviceInformationResponse.fromJson(info);
      return response;
    } catch (e) {
// Getting error: "Invalid radix-10 number"
      return GetDeviceInformationResponse.create();
    }
```
Please help how to fix it?

**Comment by gl-ihorkoblan** [comment]
Just copied source code of how it works:

```
void _mergeFromJsonMap(_FieldSet fs, Map<String, dynamic> json, ExtensionRegistry registry) {
  var keys = json.keys;
  var meta = fs._meta;
  for (var key in keys) {
    var fi = meta.byTagAsString[key];
    if (fi == null) {
      if (registry == null) continue; // Unknown tag; skip
      fi = registry.getExtension(fs._messageName, int.parse(key));// THE BUG IS HERE  **int.parse(key)**
      if (fi == null) continue; // Unknown tag; skip
    }
    if (fi.isMapField) {
      _appendJsonMap(fs, json[key], fi, registry);
    } else if (fi.isRepeated) {
      _appendJsonList(fs, json[key], fi, registry);
    } else {
      _setJsonField(fs, json[key], fi, registry);
    }
  }
}
```
As you can see the reason of the bug is in this line:
`fi = registry.getExtension(fs._messageName, int.parse(key));`

Because it tries to parse key into int, but the reason is that key is not int. key is String. It cause a bug "Invalid radix-10 number"

So please help. Maybe I'm doing something wrong? Or it's a bug?

**Comment by mraleph** [comment]
As explained on the other issue: you are most likely trying to parse Proto3 JSON as if it was a JSPB.

**Comment by fdonzello** [comment]
In my case I had to:
```dart
final jsonMap = jsonDecode(data);
final push = Push.create()..mergeFromProto3Json(jsonMap);
return push;
```

**Comment by zim32** [comment]
> In my case I had to:
> 
> ```dart
> final jsonMap = jsonDecode(data);
> final push = Push.create()..mergeFromProto3Json(jsonMap);
> return push;
> ```

Oh man thanks you saved my day. Just have the same issue right now.
I thins ot would be nice if they add new constructor Message.fromJsonProfo3 f.e.
