### ISSUE TITLE
Please add Dart to https://github.com/google/protobuf README

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/protobuf#65]

**Comment by MikeMitterer** [comment]
Link: https://github.com/google/protobuf

**Comment by skybrian** [comment]
Why?

**Comment by MikeMitterer** [comment]
Because it tells all protobuf-Users that there is a language out there named Dart! ;-)
Links as the one above tells the world that Dart is so important that as in this case a protobuf-version exists

**Comment by skybrian** [comment]
Okay, I understand now. You want to add Dart to their README file:

https://github.com/google/protobuf/blob/master/README.md

(I thought you meant moving all the source code to their repository.)

**Comment by MikeMitterer** [comment]
Yes + sorry for the confusion! + Thanks!

**Comment by postmasters** [comment]
https://github.com/google/protobuf/pull/3008
