### ISSUE TITLE
Incorrect implementation of PbList.hashcode

### ISSUE THREAD

**Issue by joshua-i** [dart-lang/protobuf#87]
PbList.hashcode intends to implement the [Jenkins hash function](https://en.wikipedia.org/wiki/Jenkins_hash_function). However, in lines like [this](https://github.com/dart-lang/protobuf/blob/3e2a439f7ea8cda5a9d8174151f715b4b94cc2b9/lib/src/protobuf/pb_list.dart#L31) it is adding before applying the bit shift. Instead of `(hash + hash << 10)` it should be something like `(hash + (hash << 10))`.

It was also suggested offline that we should change  (...) & 0x3fffffff to 0x3fffffff & (...) , though I don't fully understand why.

**Comment by rakudrama** [comment]
I recommend:

- use for-in instead of forEach
- copy the exact bit-twiddling from the private class in dart:math
- write arithmetic with the constant first, since this has more precise type inference which leads to better code.
